name: media_control
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  provider: ^6.1.1
  get_it: ^7.6.7
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
